environment:
  CURL_VERSION: 7.56.1

skip_non_tags: true
  
install:
  - git submodule update --init --recursive
  - set build_config=Release
  - call C:\projects\rematrix-filter\CI\install-build-obs-rematrix-filter.cmd

build_script:
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build64\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd C:\projects\obs-studio\
  - git describe --tags --abbrev=0 > C:\projects\obs-studio-last-tag-built.txt
  - set /p OBSLastTagBuilt=<C:\projects\obs-studio-last-tag-built.txt

before_deploy:
  - C:\projects\obs-studio\CI\before-deploy-win-rematrix-filter.cmd

deploy_script:
  - ps: cd C:\projects\rematrix-filter\
  - ps: Push-AppveyorArtifact "C:\projects\rematrix-filter\obs-studio.zip" -FileName "$(git describe --tags).zip"

test: off

cache:
  - dependencies2015.zip
  - vlc.zip
  - C:\projects\obs-studio-last-tag-built.txt
  - C:\projects\obs-studio